#!/bin/bash
#BSUB -J mas-gpt2-small
#BSUB -o logs/mas-gpt2-small_%J.out
#BSUB -e logs/mas-gpt2-small_%J.err
#BSUB -q gpua100
#BSUB -n 12
#BSUB -W 24:00
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=4096]"
#BSUB -gpu "num=1:mode=exclusive_process"

module load python3/3.12.4

source .venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r requirements.txt

wandb login "$(cat wandb/api_key.txt)"
python3 -m mechint.mas --config-name gpt2-small-oai-mlp-out.yaml params.max_time=79200 out_path=/work3/s183969/outputs/gpt2-small_mas_store wandb.project=mas-gpt2-small
