name: LaTeX

on: pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Compile Latex
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: ./report/main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf