name: LaTeX

on: pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - working-directory: report/
      - name: Compile Latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
 