name: Publish LaTeX

on:
  push:
    branches:
      - 5-check-latex-and-generate-report-in-ci

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: ./report/main.tex

      - name: Move PDF to root directory
        run: |
          mv report/main.pdf main.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          publish_dir: ./
          publish_branch: github-pages