name: Static Checks
on:
  push:
    branches:
      - main

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1

      - name: Find Trailing Whitespace
        uses: harupy/find-trailing-whitespace@v1.0

      - name: Validate YAML file
        run: yamllint abc.yml

      - name: Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "mechint"
